### ISSUE TITLE
After installation betting problem

### ISSUE THREAD

**Issue by shamimiceewu025** [FuzzyHobbit/bustabit-webserver#12]
Full Installation Process:

git clone https://github.com/moneypot/bustabit-webserver.git
cd bustabit-webserver
npm install
psql -W -U bustabit -d bustabitdb -h localhost -f server/sql/schema.sql
npm start

git clone https://github.com/FuzzyHobbit/bustabit-gameserver.git
npm install 
node populate_hashes.js
npm start

Change PORT 3841 to 8080 AND for game Server 3842 to 8880

Now Problem is Place bet. 
Gives console error: 
place_bet error:  INTERNAL_ERROR ------  engine.js:492:17
Response from placing a bet:  INTERNAL_ERROR ------- engine.js:295:25

Please Help Some One

**Comment by gittempo** [comment]
how did you resolve this issue? Just mention the solution so other peoples can get the solution there are peoples in the issues who are looking for the solution for the same

**Comment by shamimiceewu025** [comment]
In my case , their was a problem with postgresql.
working version : 9.4 & 9.5
