### ISSUE TITLE
Running the game will only run the old version

### ISSUE THREAD

**Issue by ninks01** [FuzzyHobbit/bustabit-webserver#17]
Http://bustabit.we2.be:3841/play

Installation completed
But
Running the game will only run the old version
I want to change to the new version

I do not know what to do.

**Comment by HarukaNanase** [comment]
I might be able to help you, got skype?

**Comment by shamimiceewu025** [comment]
That happened because of missing configure. For Advanced Admin panel & bugs resolve.

http://bst24.co.kr/ 
http://sline-t.com/

**Comment by alexk345** [comment]
hi shamimiceewu025 
How did you install all the servers?  Mine waiting on 3841(webserver)  382 (game server) , when i used my ipaddress:3841 nothing shows up.

**Comment by shamimiceewu025** [comment]
in my case we change port address .

**Comment by alexk345** [comment]
what is bitcoind

**Comment by shamimiceewu025** [comment]
it's a bitcoin daemon . You Need to Configure that If you want to use bitcoin as a game currency.

**Comment by alexk345** [comment]
I see instruction about gameserver / webserver / depositor. Wondering where is bitcoind.

**Comment by shamimiceewu025** [comment]
https://bitcoin.org/en/full-node read article

**Comment by shamimiceewu025** [comment]
this game , no need apache to run

**Comment by alexk345** [comment]
How does webserver knows port 3842? May be my game server not running?
> BustaBit@0.0.1 start gameserver
> node server.js --use_strict

DATABASE_URL:  postgres://bustabit:andre345@localhost:5432/bustabitdb
Listening on port  8006  with http
Have a bankroll of:  1  btc

Waiting there

**Comment by alexk345** [comment]
I checked firebug 
host/ott says unauthorized
http://18.220.6.234/socket.io/?EIO=3&transport=polling&t=LtGgLtg&sid=oDWiqjAo8prIHJIZAAAR

**Comment by ninks01** [comment]
I'm a Korean
Skype ID
Money-n.com

Please help me.
Anyone to look remotely?

**Comment by ninks01** [comment]
shamimiceewu025 님 도와주세요

**Comment by shakwon1** [comment]
@shamimiceewu025 Is it possible for me to install it?

**Comment by HarukaNanase** [comment]
I can help you easy. Add in skype ptmaxnuker

Em 13/08/2017 03:39, "shakwon1" <notifications@github.com> escreveu:

**Comment by shamimiceewu025** [comment]
@ninks01  is a scammer  . he stole my full script . But unable to run properly. Please no one help this kind of scammer.

http://one222.com/ is use that stolen script.
