### ISSUE TITLE
How can i add bot?

### ISSUE THREAD

**Issue by superstar1128** [FuzzyHobbit/bustabit-webserver#37]
I'd like to add some bots in the game.
Can I add bot? If yes, how to set number of bots?

**Comment by gittempo** [comment]
what kind of bots? chats or player bots?

**Comment by superstar1128** [comment]
both of all, chatting and playing bots

**Comment by gittempo** [comment]
yes its possible, i have my bots all time playing in bustabit.com with winning 80% winning stretagy
mail me bustabit.dev@lexcodetechnologies.com

**Comment by shamimiceewu025** [comment]
If you are a admin of game server, then you can add chat bot. https://github.com/moneypot/shiba is chat bot link.

For game bot, you need to run it via user mode. 
https://raw.githubusercontent.com/FinlayDaG33k/BustaBot/master/bot.js is sample bot

**Comment by donpawlow** [comment]
my advice for you contact with www.mg.tools  already installed  for me just 800$ with new version

**Comment by justawesome11** [comment]
jumkarry11@gmail.com
i can setup whole website for you in 10 mints with everything working like original bustabit.
i have my whole source ready,just let me know.
