### ISSUE TITLE
bustabit-depositor not working

### ISSUE THREAD

**Issue by tuckerritti** [FuzzyHobbit/bustabit-webserver#51]
I am trying to get bustabit depositor to work. 
When I run `npm run start-dev` the depositor starts but then I get this error
```Initialized on block:  0  with hash:  000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f
Unable to get block count
leaderboard refreshed
Unable to get block count```

**Comment by justawesome11** [comment]
is ur bitcoin core fully sync with current blocks?
u need to sync it completely,it takes 2-3 to completely sync before it starts working.

**Comment by tuckerritti** [comment]
the problem was I didn't have enough disk space. I allocated 60GB to my virtual machine, but the bitcoin core needs 220GB minimum to download the entire blockchain.

**Comment by justawesome11** [comment]
Great and congrats.
If u need to add more currencies or theme like nanogames.io etc.
Let me know.
Also if u have anyissues in present script.

**Comment by tuckerritti** [comment]
@justawesome11 is a fucking scammer. Stole $90 from me and then blocked me. DO NOT TRUST HIM

**Comment by bitcoinhype** [comment]
@tuckerritti are you sure, i have issue also. my deposit wont work and no idea how to do. my friend gave justawesome discord and i sent yuu friend request if u can help @justawesome11 thank

**Comment by tuckerritti** [comment]
@bitcoinhype @justawesome11 sorry i think he is offline. he is a good helper tho.

**Comment by tuckerritti** [comment]
@bitcoinhype no @justawesome11  is a fucking scammer. First of all, he tried to DDOS my server (which didn't work). He then tried to ssh to other servers on my network (didn't know all of my servers are isolated from each other). If you want his address (lives in India) or his ip address, lmk because he was a dumbass and connected to my server using his real ip.

**Comment by AllAlphacoders** [comment]
If you still need help
just reply me here.

**Comment by tuckerritti** [comment]
@AllAlphacoders I will only accept if we agree a paypal payment because no way i'm doing bitcoin again. Fucking @justawesome11

**Comment by AllAlphacoders** [comment]
ok what help you need?

**Comment by tuckerritti** [comment]
@AllAlphacoders email me -> cryptographic1337@gmail.com

**Comment by tuckerritti** [comment]
DO NOT TRUST @AllAlphacoders OR @justawesome11 
THEY ARE THE SAME PERSON AND SCAMMER.
https://gyazo.com/228c9fd74514fa6ecafa4728c995ae8e

**Comment by tuckerritti** [comment]
Can anyone else help me besides those scammers?

**Comment by adminsync** [comment]
hey what u need,how u were scammed?

**Comment by tuckerritti** [comment]
@adminsync shut the fuck up you are the same guy you created your github account 10 minutes ago

**Comment by tuckerritti** [comment]
i fixed the issue. the problem was my bitcoin core's config file was named bitcoind.conf instead of bitcoin.conf and that meant rpc was not being enabled. RPC needs to be enabled in order for the depositor to work
